; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[backup_migrate][version] = "2.5"

projects[ctools][version] = "1.3"

projects[calendar][version] = "3.4"

projects[custom_breadcrumbs][version] = "2.0-alpha3"

projects[date][version] = "2.6"

projects[ds][version] = "2.2"

projects[entity][version] = "1.1"

projects[entityreference][version] = "1.0"

projects[fences][version] = "1.0"

projects[migrate][version] = "2.5"

projects[migrate_extras][version] = "2.5"

projects[og][version] = "2.2"

projects[rules][version] = "2.3"

projects[views][version] = "3.7"

projects[wordpress_migrate][version] = "2.2"

projects[wysiwyg][version] = "2.2"

projects[smtp][version] = "1.0"

; Themes
projects[adaptivetheme][version] = "3.1"

projects[bluemasters][version] = "1.3"

projects[corkedscrewer][version] = "1.2"

projects[zen][version] = "5.1"

projects[ig_zen][type] = "theme"
projects[ig_zen][download][type] = "git"
projects[ig_zen][download][url] = "https://github.com/ithacagenerator/ig_zen.git"
